### ISSUE TITLE
we miss exist method on model 

### ISSUE THREAD

**Issue by jurajsimbs** [fogine/couchbase-odm#1]
something like 

```
model.exist(key)
```

which will return `bool` value if model isntance with `key` really exists without getting it physically from db

**Comment by fogine** [comment]
@jurajsimbs It's available on the develop branch if interested.

use case example:

````javascript
    User.exists('4f1d7ac5-7555-43cc-8699-5e5efa23cd68').then(function(exists) {...
````
The API documentation will be available once the feature is merged to the `master` with `v1.1.0` release.

**Comment by jurajsimbs** [comment]
...one small thing here... it would be cool if I was able to check existence also by some index.
For example if I have indexes defined like this:
```js
            indexes: {
                refDocs: {
                    getbyUserIdAndCodeAndCategory: { keys: [ 'user_id', 'code', 'category' ] }
                },
            }
```

...can I now check existence of model by this index? Maybe just be able to build key and then use it like 
```js
User.exists(generateKeySomehow()).then(...
```

**Comment by fogine** [comment]
Well, there is private method `Model.$buildRefDocKey()`, but it's not meant to be user-friendly as it's not part of public API.

I think I could implement public method `Model.buildRefKey`.
        Caveat of this solution is that there is currently no other way than implementing it like eg: `Model.buildRefKey('superuser', 'getByUsername')` which is not that much of good-looking solution. But it's ok for me.
