### ISSUE TITLE
Complex RefDoc not working as expected

### ISSUE THREAD

**Issue by manuel-syone** [fogine/couchbase-odm#13]
Hi! I followed the examples in your tutorial, and tried to implement the following example:

Have a model for A, a model for B, and a model the associates both of the previous, AB.

In the AB schema, I define the following:

```javascript
var AB = couchbase.define('AB',
	{
		type: DataTypes.HASH_TABLE,
		schema: {
			AId: { type: DataTypes.STRING },
			BId: { type: DataTypes.STRING },
			value: { type: DataTypes.INT, default: 0 }
		}
	},
	{
		indexes: {
			refDocs: {
				getABRelation: { keys: ['AId', 'BId'] },
			}
		}
	});
```

However, if I try to insert two models with the following keys:
Model1: {AId: "myid1", BId: "otherid1"}
Model2: {AId: "myid1", BId: "otherid2"}

The second model is inserted, but not the RefDoc, with the following error:

`Unhandled rejection StorageError: The key already exists in the server. If you have supplied a CAS then the key exists with a CAS value different than specified`.

Am I missing something here?

**Comment by fogine** [comment]
Hello @manuel-syone ,
sorry for not getting back earlier. I was a little bit in rush.

Note that reference document's keys must be unique which it looks like they are according to you models' values

Could you provide the actual code of how you try to insert documents?
Also, after the error, does the `Model2` main document remain inserted to a `bucket` without it's reference document? (Expected behavior is that if a storage error occurs during insert process, changes that have been made are rolled back)

**Comment by manuel-syone** [comment]
Hello @fogine, no problem!

Yes, they are; and I also noticed that the main documents are inserted, it's just the refDocs that fail to be inserted in the database.

Sure, here is a snippet of what I am doing.

**MODEL**
```
var couchbaseODM = require('kouchbase-odm');
var couchbaseSDK = require('kouchbase-odm/node_modules/couchbase');

var cluster = new couchbaseSDK.Cluster('couchbase://10.1.40.213:8091');
var bucket = cluster.openBucket('brandbassador');

//as simple as that
var couchbase = new couchbaseODM({
    bucket: bucket,
	schemaSettings: {
		doc: {
			idPropertyName: 'docId',
			typePropertyName: 'docType'
		}
	}
});

var DataTypes = couchbaseODM.DataTypes;

//TODO: Move Points to a complex type

var UserBrand = couchbase.define('UserBrand',
	{
		type: DataTypes.HASH_TABLE,
		schema: {
			userId: { type: DataTypes.STRING },
			brand: { type: DataTypes.STRING },
			revenue: { type: DataTypes.INT, default: 0 }
		}
	},
	{
		indexes: {
			refDocs: {
				getUserBrandRelation: { keys: ['userId', 'brand'] },
			}
		},
		timestamps: true
	});

module.exports = UserBrand;

```
**Insertion**

```
Brand.getByName(brandName).then(function(brand: any) {

    UserBrand.create({
        userId: userId,
        brand: brandName
    }).then(function(userBrand: any) {
                return reply(null, { ok: true, userBrand: userBrand });
    }).catch(function(err: any) {
        console.log(err);
        return reply(null, {
            ok: false,
            message: "An error occurred in the server"
        });
    });
})

```

Let me know if you need anything else!

**Comment by fogine** [comment]
@manuel-syone , I can't identify the problem from the code you provided - I can't see the whole execution context. Your code seems ok.
Could you please try to recreate the issue and make an [SSCCE](http://sscce.org/) ?
Also, which `version`/`branch` of the `CouchbaseODM` are you at?
What is the `node` version you're using?
Do you make any other async operations in parallel with the `UserBrand` document creation.?

**Comment by manuel-syone** [comment]
@fogine, thank you for the quick response. Let me try to get back to you at the end of the day with a SSCCE. 

Regarding the other questions:
CouchbaseODM - ^1.0.0-rc.3 on my package.json
Node Version - v4.4.7
Async operations in parallel - Yes, the problem occurrs when I am bootstrapping documents to the database

**Comment by fogine** [comment]
Oh, and I noticed that in your `Model` definition example you also create the instance of the `couchbaseODM` 
> var couchbase = new couchbaseODM({....

Do you actually instantiate a new `couchbaseODM`  object before every model schema definition?
if so, you're supposed to have one instance of the `couchbaseODM` and share it across the application.

**Comment by manuel-syone** [comment]
Thank you for the suggestion; my idea was to have that code in a different file and `require` it in every model - would that solve the problem? 

We have a micro-services architecture, perhaps another option would be to instantiate couchbaseODM at the service level and pass the instance to each required model, does this make sense to you?

**Comment by fogine** [comment]
>Thank you for the suggestion; my idea was to have that code in a different file and require it in every model - would that solve the problem?

That's the way how it should be. It may cause issues when dealing with document relations and such... From the information I have about your code I can't be sure if it's the root problem, however I would strongly suggest to change the design so it uses only one `couchbaseODM` instance for all Models per `nodejs` process.

There is available the `v1.0.0` release of the ODM on the github which is not yet available on the `npm` (will be soon), could you test your application with:
`"kouchbase-odm": "https://github.com/fogine/couchbase-odm.git#master"`
in your `package.json` ?

**Comment by manuel-syone** [comment]
Thank you very much for your help. Let me get back to you later in this day; I will be sure to try the latest version of couchbase.

**Comment by fogine** [comment]
Has been the issue resolved, @manuel-syone ?

**Comment by manuel-syone** [comment]
Hi @fogine ! Sorry for not answering sooner, I haven't had the time to set up an example and test this. I let you know once I have something concrete to show!

**Comment by manuel-syone** [comment]
Hi @fogine! Sorry for the delay on my answer; things have been chaotic. We now only instantiate the ODM once per node process, but we ended up following an approach in which the error is not reproduceable. 

I can say for sure that using the code above using the `master` branch of the repository does not cause any errors, so I am guessing that I was probably doing something wrong. If I come up with the error again, I will reopen the issue.

Again, thank you for all your work and help, it is very much appreciated :+1:
