### ISSUE TITLE
Error when updating document

### ISSUE THREAD

**Issue by TelmaFernandes** [fogine/couchbase-odm#14]
When I try to update an existing document using the update method, it returns: "Cannot read property '$buildRefDocument' of null".

This is the code I'm using:

```
User.getById(request.user.userId).then((user: any) => {
		user.update(request.user).then((user: any) => {
			return reply(null, { ok: true, user: user });
		}).catch((err: any) => {
			return reply(null, { ok: false, message: err.message });
		});
	}).catch((err: any) => {
		return reply(null, { ok: false, message: 'User does not exist' });
	});
```

**Comment by fogine** [comment]
Hello,
thanks for the bug report @TelmaFernandes ! The bugfix is available in the `v1.0` or `develop` branch.
The `v1.0.1` will be released soon with the fix.
