### ISSUE TITLE
DataTypes.COMPLEX not working as expected

### ISSUE THREAD

**Issue by mreis92** [fogine/couchbase-odm#19]
Hello @fogine ! I have setup the following models, each one in a different file (omitted some properties for the sake of clarity):

```
var UserSettings = couchbase.define('UserSettings',
    {
        type: DataTypes.HASH_TABLE,
        default: {},
        schema: {
              someValue1: { type: DataTypes.NUMBER, default: 0 }
              someValue2: { type: DataTypes.NUMBER, default: 1 }
        }
    }
```

```
var User = couchbase.define('User',
    {
        type: DataTypes.HASH_TABLE,
        schema: {
            name: { type: DataTypes.STRING }
            settings: {
                type: DataTypes.COMPLEX('UserSettings')
            },
        }
    }
```
Both of the models are defined with the same ODM instance. When I try to execute the following command: `User.create({name: "test"})`, the following error occurs: 
```
{ [ValidationError: settings value can NOT be empty (undefined or null)]
  name: 'ValidationError',
  message: 'settings value can NOT be empty (undefined or null)' }
```

Am I missing something? I have tried to use the `default` property both in the model and in the property.

**Comment by fogine** [comment]
Hello @mreis92 ,

This has not been fully implemented yet... and so if you provide default `UserSettings` object for the `settings` property, the exact same `UserSettings` object will be used as default value for every new `User` object... which is not the desired behavior. Eg.:  
```javascript
var User = couchbase.define('User',
    {
        type: DataTypes.HASH_TABLE,
        schema: {
            name: { type: DataTypes.STRING }
            settings: {
                 type: DataTypes.COMPLEX('UserSettings'),
                 default: UserSettings.build(),  // like so
            },
        }
    }
```

 Model associations feature still needs work.

**Comment by fogine** [comment]
Thanks for the bug report @mreis92  ! The bugfix is available in the `v1.0` or `develop` branch. 
The following should work now:

```javascript

var User = couchbase.define('User',
    {
        type: DataTypes.HASH_TABLE,
        schema: {
            name: { type: DataTypes.STRING }
            settings: {
                 type: DataTypes.COMPLEX('UserSettings'),
                 default: UserSettings.build(),  //
            },
        }
    }
```

The default `UserSettings` object will be cloned for every new `User` instance object and set as the default value. Keep in mind, that the `UserSettings`  instance object set as default value is "cloned as is" without any additional changes to the cloned object.

**Comment by mreis92** [comment]
Hi @fogine . Thank you for the quick reply! I'll try to have it tested until the end of the day!

**Comment by fogine** [comment]
Could you please test again on the `v1.0` branch, @mreis92 ?
Thank  you!

**Comment by mreis92** [comment]
Hi @fogine! I've tested in the `v1.0` branch. The user is created, and there is a key to a Settings document:

```
"settings": {
    "docId": "Settings::91f778c3-4eca-462f-b3b8-eb1273ff01b9"
  }
```

but there isn't any Settings document. I was actually thinking that the approach above would simply embed the Settings in the User (as a way to divide your model in different modules that could be reused by other models).

The following error was caught by the application:

Cannot read property 'data' of undefined at Instance.toJSON (/node_modules/kouchbase-odm/lib/instance.js:834:40)")

**Comment by fogine** [comment]
>The user is created, and there is a key to a Settings document.

This is desired behavior. The `DataTypes.COMPLEX()` accepts option object as second argument where it's possible to set relation type, it defaults to `RelationType.REFERENCE`. 
 Currently only relation by `reference` is implemented. It's possible to implement another relation type in the future eg.: `RelationType.EMBEDED` however I haven't thought it's useful enough... why split something that's going to be put together when inserting it to a bucket? 

Or can you think of any other user case where it would be helpful, @mreis92 ?

About the error, could you please create a new issue with full error [stack trace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack) and describe when it happens (code example)? 
Thank you @mreis92 .

**Comment by mreis92** [comment]
Hello @fogine! 
My opinion of the benefits of the EMBEDDED type is just that you are able to reuse parts of the model that may be common among other models (e.g. a Company model and a User model may have embedded an Address model).

Unfortunately, at this point I don't have much time to provide a new code example (I have moved on to another task in the project :) ). As soon as I have time again I will get back to you, if that's okay.

Thank you for your time!
