### ISSUE TITLE
getById does not return docType

### ISSUE THREAD

**Issue by TelmaFernandes** [fogine/couchbase-odm#21]
Hello, 

When I try to get a document with the method getById, the method returns all the fields of the document except for the docType field.

**Comment by fogine** [comment]
Could you please clarify further, @TelmaFernandes ?

**Comment by TelmaFernandes** [comment]
@fogine ,

I'm using the **develop** branch and I have the following document:

```
var Person = couchbase.define('Person', {
   type: DataTypes.HASH_TABLE,
   schema: {
      name: { type: DataTypes.STRING }
   }
},
{
timestamps: true
});
```
**Note:** I edited the schema settings in order for the _idPropertyName_ be docId and the _typePropertyName_ be docType.

When I create a Person it generates (for example) a document with the following fields:

```
{
  "name": "Telma",
  "docId": "0b8ad79a-d86f-4a10-a042-7d5a61bb4ba3",
  "docType": "Person",
  "created_at": "2016-09-07T09:24:29Z",
  "updated_at": "2016-09-07T09:24:29Z"
}
```

And when I do this:

```
Person.getById("0b8ad79a-d86f-4a10-a042-7d5a61bb4ba3").then(function (person) {
   return person;
});
```
It returns:

```
{
  "name": "Telma",
  "docId": "0b8ad79a-d86f-4a10-a042-7d5a61bb4ba3",
  "created_at": "2016-09-07T09:24:29Z",
  "updated_at": "2016-09-07T09:24:29Z"
}
```

As you can see all the fields are there except for docType.

Hope this helps. 

Thanks! :smiley:

**Comment by fogine** [comment]
Oh, I see. Actually, I did that that way on purpose. 
The rationale has been that when you invoke the `toJSON` method on an `Instance` object you don't want to get internal properties except a document's id.

On the returned `person` object, there is still `docType` property and if you call person.getData(), you will get all data including all internal properties... 

Does that makes sense to you, @TelmaFernandes ?

I suppose, later on you pass the `person` object to the `express` or similar framework... something like: 
```javascript
function(req, res, next) {
  //.. get person
  return res.json(person);
}
```

if that's the case and you still want to get the `docType` property, calling `person.getData()` should solve the problem...

**Comment by TelmaFernandes** [comment]
Hi, @fogine  

Yes, it makes sense. It works with the `getData()`! 

Thank you very much! :smile:
