### ISSUE TITLE
we need proper n1q1 example!

### ISSUE THREAD

**Issue by jurajsimbs** [fogine/couchbase-odm#4]
Please complete this peace of ... nothing (!!) here:
https://fogine.github.io/couchbase-odm/tutorial-3d.n1ql.html

**Comment by fogine** [comment]
Hello,
the `n1ql` documentation section will be updated once `n1ql` support is implemented.
Currently  there are no `n1ql` features implemented in the `ODM`.

However, there is available `Promise` based method [StorageAdapter.query](https://fogine.github.io/couchbase-odm/StorageAdapter.html#query) which is using native [couchbase sdk query method](http://docs.couchbase.com/sdk-api/couchbase-node-client-2.0.0/Bucket.html#query) through which you can execute `n1ql` / `view` queries in meantime.

**Comment by jurajsimbs** [comment]
!!! then delete this method from sources - I was confused!
https://github.com/fogine/couchbase-odm/blob/master/lib/storageAdapter.js#L360-372

![c20d95a9be009c21466a96fa850e79606985b1e83c90ca3981fd7f77c6b78854](https://cloud.githubusercontent.com/assets/18613927/16142700/ea260570-3467-11e6-9488-711f98e53d8e.jpg)

**Comment by fogine** [comment]
Oh, You're right that I could stress existence of the `StorageAdapter.query` method in the tutorial section of the docs.
> Currently (as for v1.0-rc.3) there are no n1ql features implemented in the ODM.

I meant features which would bring additional value / functionality which is not available in native couchbase sdk. `StorageAdapter.query` is just Promise based variant of `Bucket.query` from native couchbase sdk.

I'll add note about the method to the tutorial section.
Thanks.
