### ISSUE TITLE
possibility to just send custom id key during creation

### ISSUE THREAD

**Issue by jurajsimbs** [fogine/couchbase-odm#5]
it would be cool to have an option to send _id directly with `.create` command - without all that fuss about `customKeySomething...` (which is cool but little too overkill if we just want to write object with some specific id)
Like in SQL you have multiple options with keys:
- enter it directly
- omit it and it will be autogenerated (if you wish)
- omit it and some generator will be used to generate it (pgsql and oracle and mysql with some triggers)

**Comment by fogine** [comment]
@jurajsimbs It's available on the `develop` branch if interested.

use case example:

```javascript
    var key = User.buildKey('4f1d7ac5-7555-43cc-8699-5e5efa23cd68');
    User.create({username: 'juraj'}, {key: key}).then...

    // or

    User.create({username: 'juraj'}, {key: '4f1d7ac5-7555-43cc-8699-5e5efa23cd68'}).then...
````

The API documentation will be available once the feature is merged to `master`.

**Comment by jurajsimbs** [comment]
working nicely - also with custom key :+1:

**Comment by jurajsimbs** [comment]
....one teeny-weeny thing... lets say I want to create generic RegExp key like this
```js
var RegexpKey = function(options) {
    Key.call(this, options)
}
util.inherits(RegexpKey, Key)

RegexpKey.prototype.setId = function(id) {
    if (id !== undefined) {        
        ///HOW can I get to that regexp param??
        if ((id + '').match(this.options.regexp) === null) {
            throw new KeyError('Failed to set `id`. The value is not in correct format: ' + id);
        }
    }
    this.super.setId.call(this, id);
}

RegexpKey.dataType = DataTypes.STRING
```

and then use it domehow like
```js
key: RegexpKey({regexp: /^[0-9a-f]{20}$/i})
```

any idea? In current implementation I do not see how can I pass options (or some params) into key object...
I can do that with node (for example) mySuperKey.js:
```js
var regexpkey = function(regexp) {
  ///key def
}
module.exports = regexpkey
```
and then use it like
```js
key: require('/my/super/regexp/mySuperKey')(regexp: /^[0-9a-f]{20}$/i)
```

...but i do not like this approach... or is it ok?

**Comment by fogine** [comment]
> any idea? In current implementation I do not see how can I pass options (or some params) into key object...

In this case, it's ok to pass additional options of the `RegexpKey` to the `options.schemaSettings.key` options object when defining a Model, like so:

````js
    var User = couchbase.define('User', {
        type: DataTypes.HASH_TABLE
    }, {
        schemaSettings: {
            key: {
                regexp: /^[0-9a-f]{20}$/i
            }
        }
    });
````

Then:

````js
    User.buildKey('id'); // will be instantiated with additional regexp option.
````

Note that you must handle the custom option yourself in `RegexpKey` construstor.

**Comment by jurajsimbs** [comment]
okay working nicely :+1: 
I'll add regexp key later as pull request... found this wonderful lib for generating strings from regexps 
https://www.npmjs.com/package/randexp
so autogenerated keys should work too
