### ISSUE TITLE
abstract contructor

### ISSUE THREAD

**Issue by jurajsimbs** [fogine/couchbase-odm#9]
constructor in
https://github.com/fogine/couchbase-odm/blob/master/lib/hook.js#L31

should throw error (because it is defined as abstract) to avoid direct call

**Comment by fogine** [comment]
Hook methods are bound to static object so It should throw a `TypeError` if you try to extend it  as `Hook` object does not have any `prototype` set. It's not possible to instantiate new `Hook` object as well. The thing is, the `Hook` object should not be a part of public `API`. I'll remove it.

**Comment by jurajsimbs** [comment]
ah yes you're right. I totally overlooked it was static... my bad.
